#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
cd $DIR/..

echo "$SCRIPT: start"

echo "$SCRIPT: checking git..."
git checkout package-lock.json
git status 2> /dev/null | grep "nothing to commit"; RC=$?
if [ "$RC" == "0" ]; then
  echo "$SCRIPT: git is clean (OK)"
else
  echo "$SCRIPT: git is NOT clean (CANCELED)"
  git status
  exit -1
fi

export BABEL_ENV=deploy
nuxt --version
$DIR/nuxt-routes.js
export CI=
echo CI=$CI
nuxt generate
$DIR/git-commit-version PUSH
npm run deploy:branch 
RC=$?

echo "$SCRIPT: done => $RC"
