#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

${DIR}/install-node16 &&
${DIR}/update-npm &&
${DIR}/install-ripgrep &&
npm install && 
echo -e "${SCRIPT}: completed (OK)"
