#!/bin/bash

type rg 2>&1 > /dev/null; RC=$?
if [ "$RC" == "0" ]; then
  echo -e "INSTALL\t: " `rg --version 2>&1 | head -1` "(OK)"
else
  echo -e "INSTALL\t: installing ripgrep"
  curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
  sudo dpkg -i ripgrep_12.1.1_amd64.deb
fi
