#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
cd $DIR/..

UPSTREAM=https://github.com/ebt-site/ebt-vue.git
echo "$SCRIPT: pulling $UPSTREAM"
git config remote.upstream.url $UPSTREAM
git config remote.upstream.fetch +refs/heads/*:refs/remotes/upstream/*
git pull upstream main
