#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
cd $DIR/..

echo "$SCRIPT: start"

echo "$SCRIPT: checking git..."
git checkout package-lock.json
git status 2> /dev/null | grep "nothing to commit"; RC=$?
if [ "$RC" == "0" ]; then
  echo "$SCRIPT: git is clean (OK)"
else
  echo "$SCRIPT: git is NOT clean (CANCELED)"
  git status
  exit -1
fi

export BABEL_ENV=deploy
nuxt --version

echo "$SCRIPT: wiki-images"
$DIR/wiki-images; RC=$? || exit $RC

echo "$SCRIPT: nuxt-routes"
$DIR/nuxt-routes.js; RC=$? || exit $RC

echo "$SCRIPT: nuxt generate"
export CI=
echo CI=$CI
nuxt generate; RC=$? || exit $RC

echo "$SCRIPT: git-commit-version"
$DIR/git-commit-version PUSH; RC=$? 
if [ "$RC" == "411" ]; then
  echo "$SCRIPT: no changes (ok)"
elif [ "$RC" == "0" ]; then
  echo "$SCRIPT: changes committed (ok)"
else
  echo "$SCRIPT: ERROR $RC"
fi

npm run deploy:branch ; RC=$? || exit $RC

echo "$SCRIPT: done => $RC"
exit $RC
