#!/usr/bin/env node

const RepoInfo = require('ebt-vue/src/repo-info');

(async function(){
  let info = await RepoInfo.info();
  let json = JSON.stringify(info, null, 2);
  let yaml = Object.keys(info).map(key => `${key}: ${info[key]}`);
  console.log(json);
})();
