#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
cd $DIR/..

MSG=`type curl`; RC=$?
if [ "$RC" == "0" ]; then
  echo "$SCRIPT: curl found (ok)"
else
  echo "$SCRIPT: installing curl"
  sudo apt-get install curl
fi

MSG=`type json`; RC=$?
if [ "$RC" == "0" ]; then
  echo "$SCRIPT: json found (ok)"
else
  echo "$SCRIPT: installing json"
  sudo npm install -g json
fi

ACCOUNT=`$DIR/repo-info | json account`
REPO=`$DIR/repo-info | json repository`
UPSTREAM=`curl -s https://api.github.com/repos/$ACCOUNT/$REPO | json parent.full_name`
echo "$SCRIPT: ACCOUNT:$ACCOUNT REPO:$REPO UPSTREAM:$UPSTREAM"

if [ "$UPSTREAM" == "" ]; then
  echo "$SCRIPT: No upstream repository (ok)"
  $DIR/build PUSH; RC=$? || exit $RC
  $DIR/push-action; RC=$? || exit $RC
else
  echo "$SCRIPT: pulling from upstream repository $UPSTREAM"
  git config remote.upstream.url https://github.com/$UPSTREAM.git
  git config remote.upstream.fetch +refs/heads/*:refs/remotes/upstream/*
  git pull -X ours --no-edit upstream main; RC=$? || exit $RC
  echo "$SCRIPT: committing upstream changes"
  git push; RC=$? || exit $RC

  echo "$SCRIPT: npm install"
  npm install
fi

$DIR/push-action
