#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
cd $DIR/..

echo "$SCRIPT: touching content files to date of last change"
find content -type f | \
xargs -I '{}' bash -c \
'DATE=`git log -1 --pretty="format:%cI" {}`; touch -d "$DATE" {}; echo $DATE {}'
